FROM openresty/openresty:latest

LABEL maintainer="Ferimer DevTeam <devteam@ferimer.es>"
LABEL ferimer_service="nginx-proxy"

RUN ln -s /etc/nginx/conf.d/ /usr/local/openresty/nginx/conf.d

EXPOSE 443
